spring.application.name=sport-booking-service
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/sport_booking}
spring.datasource.username=${DATABASE_USERNAME:sport_booking}
spring.datasource.password=${DATABASE_PASSWORD:sport_booking}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
